// Generated by Python Script for STM32F4 + LCD1602
// Source: D:\LEARNING\XJTLUCHIPS\MES303TC\MES303TC\demo.gif.url
// Total Frames: 0
// Size: 0 Bytes

#include <stdint.h>

const uint32_t TOTAL_FRAMES = 0;

const uint8_t VIDEO_DATA[0][32] = {
};
